export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  HOW_IT_WORKS: "/how-it-works",
  MARKETPLACE: "/marketplace",
  CONTACT: "/contact",
  FAQ: "/faq",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_ACCOUNT: "/verify-account",
  FARMER_DASHBOARD: "/farmer/dashboard",
  FARMER_PRODUCTS: "/farmer/products",
  FARMER_ADD_PRODUCT: "/farmer/products/add",
  FARMER_EDIT_PRODUCT: "/farmer/products/edit/:id",
  FARMER_PRODUCT_DETAILS: "/farmer/products/:id",
  FARMER_ORDERS: "/farmer/orders",
  FARMER_ORDER_DETAILS: "/farmer/orders/:id",
  FARMER_EARNINGS: "/farmer/earnings",
  FARMER_REPUTATION: "/farmer/reputation",
  FARMER_VERIFICATION: "/farmer/verification",
  FARMER_ESCROW: "/farmer/escrow",
  FARMER_MESSAGES: "/farmer/messages",
  FARMER_NOTIFICATIONS: "/farmer/notifications",
  FARMER_PROFILE: "/farmer/profile",
  FARMER_SETTINGS: "/farmer/settings",
  BUYER_DASHBOARD: "/buyer/dashboard",
  BUYER_MARKETPLACE: "/buyer/marketplace",
  BUYER_PRODUCT_DETAILS: "/buyer/products/:id",
  BUYER_CART: "/buyer/cart",
  BUYER_CHECKOUT: "/buyer/checkout",
  BUYER_ORDERS: "/buyer/orders",
  BUYER_ORDER_DETAILS: "/buyer/orders/:id",
  BUYER_FAVORITES: "/buyer/favorites",
  BUYER_FARMERS: "/buyer/farmers",
  BUYER_REPUTATION: "/buyer/reputation",
  BUYER_ESCROW: "/buyer/escrow",
  BUYER_MESSAGES: "/buyer/messages",
  BUYER_NOTIFICATIONS: "/buyer/notifications",
  BUYER_PROFILE: "/buyer/profile",
  BUYER_SETTINGS: "/buyer/settings",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAILS: "/admin/users/:id",
  ADMIN_VERIFICATION_REQUESTS: "/admin/verification-requests",
  ADMIN_TRANSACTIONS: "/admin/transactions",
  ADMIN_ESCROW: "/admin/escrow",
  ADMIN_DISPUTES: "/admin/disputes",
  ADMIN_REPORTS: "/admin/reports",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_SETTINGS: "/admin/settings",
  DEV_COMMON: "/dev/common",
  DEV_LAYOUTS: "/dev/layouts",
};

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.ABOUT,
  ROUTES.HOW_IT_WORKS,
  ROUTES.MARKETPLACE,
  ROUTES.CONTACT,
  ROUTES.FAQ,
  ROUTES.PRIVACY,
  ROUTES.TERMS,
];

export const AUTH_ROUTES = [
  ROUTES.LOGIN,
  ROUTES.REGISTER,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.RESET_PASSWORD,
  ROUTES.VERIFY_ACCOUNT,
];
